name: Secrets Demo

on:
  workflow_dispatch:

jobs:
  secrets-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check secret presence
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is NOT set"
          fi

      - name: Try printing secret (masked)
        run: echo "${{ secrets.MY_SECRET_MESSAGE }}"

      - name: Use secret as env variable
        env:
            SECRET_MSG: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
            echo "Using secret safely (length): ${#SECRET_MSG}"   